### ISSUE TITLE
Blue screen of error reading memory address

### ISSUE THREAD

**Issue by baby0o01999** [can1357/NtLua#10]
```lua
     read8(0xfffff8006536fd40) --Wrong address, read blue screen
```

Can I add _try _except to all memory reads and writes?

**Comment by baby0o01999** [comment]
Memory functions read_n write_n ...,use nt.MmIsAddressValid to detect memory errors

**Comment by can1357** [comment]
Try catch or except will not catch invalid memory access if the pointer is in kernel mode :)

**Comment by can1357** [comment]
You can use "readvs" instead which is at https://github.com/can1357/NtLua/blob/8a88fef9b8e6e1528f9a200f2026557dc1b9e8a4/KernelLuaVm/lua/api.cpp#L109
