### ISSUE TITLE
Now do the same for javascript

### ISSUE THREAD

**Issue by Trojaner** [can1357/NtLua#2]
As you may already know the ultimate best programming language in the world, JavaScript, first took over the browers. Next it took over servers with node.js and then it took over desktops with electron. But on desktops it is limited to user space and now it has the potential to take over kernel space too!!!

NO ONE CAN STOP JAVASCRIPT FROM CONQUERING THE WHOLE WORLD

**Comment by can1357** [comment]
yes

**Comment by wonderzdh** [comment]
It seems very difficult to port the JavaScript virtual machine to the kernel. After all, Lua is simple.

**Comment by unforseenconsequ3nces** [comment]
Lua already conquered the entire world. His army is too big... javascript must surrender and go to browser jail where it will be locked up to only run on browsers. NodeJS will still be free.
