### ISSUE TITLE
Memory requisition is always 0

### ISSUE THREAD

**Issue by baby0o01999** [can1357/NtLua#8]
local address = nt.ExAllocatePoolWithTag(0, 100, 0)
print("address",address)

D:\drv\ntlua>ntlua readmem.lua
Running 'readmem.lua'...
address 0

---------------------------
windows 10 professional edition 18362.145

**Comment by can1357** [comment]
I think this has to do with Tag=0, try using the exported "malloc" instead which does ExAllocatePool( NonPagedPool, n );

**Comment by baby0o01999** [comment]
> ExAllocatePool

ExAllocatePool is ok.

**Comment by can1357** [comment]
👍
