### ISSUE TITLE
Require causes a blue screen

### ISSUE THREAD

**Issue by baby0o01999** [can1357/NtLua#9]
Require causes a blue screen

test.lua
```lua
print("test")
```

1.lua
```lua
require("test.lua") --Require causes a blue screen

```

-----------------------------windbg info----------------------------

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 18362 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Kernel base = 0xfffff803`34600000 PsLoadedModuleList = 0xfffff803`34a432b0
Debug session time: Tue Sep 14 03:07:41.721 2021 (UTC + 11:00)
System Uptime: 0 days 0:02:37.642
Loading Kernel Symbols
...............................................................
................................................................
..............................
Loading User Symbols
Loading unloaded module list
......
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff803`347bc8a0 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffff88f`7af80b50=0000000000000050
4: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

PAGE_FAULT_IN_NONPAGED_AREA (50)
Invalid system memory was referenced.  This cannot be protected by try-except.
Typically the address is just plain bad or it is pointing at freed memory.
Arguments:
Arg1: fffff88f7af81006, memory referenced.
Arg2: 0000000000000002, value 0 = read operation, 1 = write operation.
Arg3: fffff8033fac43ae, If non-zero, the instruction address which referenced the bad memory
	address.
Arg4: 0000000000000002, (reserved)

Debugging Details:
------------------

*** WARNING: Unable to verify timestamp for KernelLuaVm.sys

Could not read faulting driver name

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 5

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on E5_1

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 16

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 69

    Key  : Analysis.System
    Value: CreateObject

BUGCHECK_CODE:  50

BUGCHECK_P1: fffff88f7af81006

BUGCHECK_P2: 2

BUGCHECK_P3: fffff8033fac43ae

BUGCHECK_P4: 2

READ_ADDRESS: fffff80334b6e3b0: Unable to get MiVisibleState
Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
fffff80334a253b8: Unable to get Flags value from nt!KdVersionBlock
fffff80334a253b8: Unable to get Flags value from nt!KdVersionBlock
unable to get nt!MmSpecialPagesInUse
 fffff88f7af81006 

MM_INTERNAL_CODE:  2

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  ntlua.exe

TRAP_FRAME:  fffff88f7af80df0 -- (.trap 0xfffff88f7af80df0)
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=fffff88f7af81000 rbx=0000000000000000 rcx=fffff88f7af81006
rdx=ffff87761c13c370 rsi=0000000000000000 rdi=0000000000000000
rip=fffff8033fac43ae rsp=fffff88f7af80f88 rbp=fffff8033fac7670
 r8=0000000000000006  r9=ffff8802575f5d07 r10=fffff8033fac7670
r11=0000000000000065 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na po nc
KernelLuaVm+0x243ae:
fffff803`3fac43ae 448819          mov     byte ptr [rcx],r11b ds:fffff88f`7af81006=00
Resetting default scope

BAD_STACK_POINTER:  fffff88f7af80b48

STACK_TEXT:  
fffff88f`7af80b48 fffff803`347dfd54 : 00000000`00000050 fffff88f`7af81006 00000000`00000002 fffff88f`7af80df0 : nt!KeBugCheckEx
fffff88f`7af80b50 fffff803`3467aaef : 00000000`00000000 00000000`00000002 00000000`00000000 fffff88f`7af81006 : nt!MiSystemFault+0x1d2d64
fffff88f`7af80c50 fffff803`347ca79a : 00000000`00000000 00000000`00000000 00000000`00000001 00000000`00000000 : nt!MmAccessFault+0x34f
fffff88f`7af80df0 fffff803`3fac43ae : fffff803`3faa3357 00000000`00000007 ffff8005`970bd370 00000000`00000000 : nt!KiPageFault+0x35a
fffff88f`7af80f88 fffff803`3faa3357 : 00000000`00000007 ffff8005`970bd370 00000000`00000000 00000000`00000000 : KernelLuaVm+0x243ae
fffff88f`7af80f90 00000000`00000007 : ffff8005`970bd370 00000000`00000000 00000000`00000000 00000000`00000001 : KernelLuaVm+0x3357
fffff88f`7af80f98 ffff8005`970bd370 : 00000000`00000000 00000000`00000000 00000000`00000001 fffff803`3faa3f98 : 0x7
fffff88f`7af80fa0 00000000`00000000 : 00000000`00000000 00000000`00000001 fffff803`3faa3f98 ffff8005`970bd370 : 0xffff8005`970bd370

SYMBOL_NAME:  KernelLuaVm+243ae

MODULE_NAME: KernelLuaVm

IMAGE_NAME:  KernelLuaVm.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  243ae

FAILURE_BUCKET_ID:  AV_INVALID_STACKPTR_ERROR_KernelLuaVm!unknown_function

OS_VERSION:  10.0.18362.1

BUILDLAB_STR:  19h1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {f899ac6c-bbb1-db6f-0783-783a184fd4ab}

Followup:     MachineOwner
---------

**Comment by can1357** [comment]
Filesystem is not supported yet, so require won't work.
